# Color extraído de tu imagen (Lavanda/Púrpura)
background #a193b0

# Nivel de transparencia (0.8 es un buen equilibrio)
background_opacity 0.50

# Opcional: Elimina el difuminado si quieres que sea vea más claro
# background_blur 0

