background {
    monitor =
    path = /home/maxioten/Pictures/Fondo.jpg

    blur_passes = 0
    blur_size = 0

    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(255,255,255,1.0)
    font_size = 95
    font_family = Sans Bold

    position = 0, 220

    halign = center
    valign = center
}

shape {
    monitor =
    size = 420, 120
    color = rgba(0,0,0,0.12)
    rounding = 20

    position = 0, 40

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] ~/.config/hypr/media.sh | sed -n '1p'

    color = rgba(255,180,180,1.0)

    font_size = 16
    font_family = Sans Bold

    position = 0, 72

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] ~/.config/hypr/media.sh | sed -n '2p'

    color = rgba(255,255,255,1.0)

    font_size = 22
    font_family = Sans Bold

    position = 0, 42

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] ~/.config/hypr/media.sh | sed -n '3p'

    color = rgba(220,220,220,0.8)

    font_size = 16
    font_family = Sans

    position = 0, 12

    halign = center
    valign = center
}

input-field {
    monitor =

    size = 320, 55

    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(255,255,255,0.25)
    inner_color = rgba(0,0,0,0.2)
    font_color = rgba(255,255,255,1.0)

    fade_on_empty = false
    hide_input = false

    rounding = 20

    placeholder_text = Input Password...

    position = 0, -120

    halign = center
    valign = center
}	
