monitr=,preferred,auto,auto

exec-once = waybar &
exec-once = hypridle
disable_hyprland_qtutils_check = true
exec-once = mpvpaper -o "loop --no-audio" HDMI-A-2 ~/Downloads/anime1.mp4
bind = SUPER SHIFT, W, exec, killall waybar || waybar
$mainMod = SUPER
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindl = , XF86AudioMute, exec, pamixer -t
exec-once = swayosd-server 
bindl = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindl = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindl = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
input {
 kb_layout = es
}

general {
   gaps_in = 5
   gaps_in = 10 
   border_size = 2
}

decoration {
   rounding = 5
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
    }
} 

animations {
    enabled = yes

    bezier = smooth, 0.25, 0.1, 0.25, 1.0

    animation = windows, 1, 7, smooth
    animation = fade, 1, 7, smooth
    
    # Aquí añadimos 'slidevert' para el movimiento vertical
    animation = workspaces, 1, 6, smooth, slidevert
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
}

bind = SUPER, A, exec, pkill wofi || wofi --show drun
bind = SUPER, K, exec, pkill wofi || ~/.config/hypr/scripts/keybinds.sh
bind = SUPER, T, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER SHIFT, M, exit
bind = SUPER, N, exec, mpc clear && mpc add / && mpc play
bind = SUPER, E, exec, dolphin
bind = SUPER, D, exec, discord
bind = SUPER, P, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, B, exec, ~/Downloads/Helium.AppImage
bind = SUPER, Y, exec, ~/Downloads/Helium.AppImage https://youtube.com
bind = SUPER, U, exec, ~/Downloads/Helium.AppImage https://eva.interior.udelar.edu.uy/
bind = SUPER, H, exec, ~/Downloads/Mangayomi.AppImage
bind = SUPER, W, exec, flatpak run io.github.mimbrero.WhatsAppDesktop
bind = SUPER, O, exec, mpc play
bind = SUPER, X, exec, mpc stop
bind = SUPER, SPACE, exec, mpc toggle
bind = SUPER, RIGHT, exec, mpc next
bind = SUPER, LEFT, exec, mpc prev
bind = $mainMod, F, fullscreen, 0
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, UP, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && swayosd-client --output-volume raise
bind = SUPER, DOWN, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% && swayosd-client --output-volume lower
bind = SUPER, M, exec, swayosd-client --output-volume mute-toggle
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod ALT, 1, movetoworkspacesilent, 1
bind = $mainMod ALT, 2, movetoworkspacesilent, 2
bind = $mainMod ALT, 3, movetoworkspacesilent, 3
bind = $mainMod ALT, 4, movetoworkspacesilent, 4
bind = $mainMod ALT, 5, movetoworkspacesilent, 5
bind = $mainMod ALT, 6, movetoworkspacesilent, 6
bind = $mainMod ALT, 7, movetoworkspacesilent, 7
bind = $mainMod ALT, 8, movetoworkspacesilent, 8
bind = $mainMod ALT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, mouse_down, movetoworkspace, e+1
bind = $mainMod SHIFT, mouse_up, movetoworkspace, e-1
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
env = XDG_MENU_PREFIX,arch-
